tripod/blog/urls.py
from django.urls import path, include

from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.tripodPage, name='tripodPage'),
    path('contact', views.contactPage, name='contactUs'),
    path('features', views.featuresPage, name='features'),
]

tripod/company/urls.py
from django.urls import path

from company import views

app_name = 'company'

urlpatterns = [
    # company pages urls
    path('', views.staffCompanyHomePage, name='staffCompany'),
    path('login/', views.staffLoginPage, name='staffLogin'),
    path('logout/', views.staffLogoutPage, name='staffLogout'),
    path('<int:pk>', views.companyUpdate, name='companyUpdate'),
    path('account', views.updateProfile, name='updateProfile'),
    path('account/change_password',
         views.changePassword,
         name='changePassword'),
    # Employee management
    path('employeeManagement',
         views.employeeManagementPage,
         name='employeeManagement'),
    path('employeeManagement/employee/<int:pk>',
         views.staffUpdatePage,
         name='employeeUpdatePage'),
    path('clientManagement/employee/delete/<int:pk>',
         views.userDeletePage,
         name='employeeDeletePage'),
    path('employeeManagement/employee/add/',
         views.staffAddPage,
         name='employeeAdd'),

    # User management
    path('clientManagement',
         views.clientManagementPage,
         name='clientManagement'),
    path('clientManagement/client/<int:pk>',
         views.clientUpdatePage,
         name='clientUpdatePage'),
    path('clientManagement/client/delete/<int:pk>',
         views.userDeletePage,
         name='clientDeletePage'),
    path('clientManagement/client/add/', views.clientAddPage,
         name='clientAdd'),

    # Event management
    path('packageManagement/events',
         views.eventManagement,
         name='eventManagement'),
    path('packageManagement/event/add/', views.eventAddPage, name='eventAdd'),
    path('packageManagement/event/<int:pk>',
         views.eventUpdatePage,
         name='eventUpdate'),
    path('packageManagement/event/delete/<int:pk>',
         views.eventDeletePage,
         name='eventDelete'),

    # Product Management
    path('packageManagement/products',
         views.productManagement,
         name='productManagement'),
    path('packageManagement/product/add/',
         views.productAddPage,
         name='productAdd'),
    path('packageManagement/product/<int:pk>',
         views.productUpdatePage,
         name='productUpdate'),
    path('packageManagement/product/delete/<int:pk>',
         views.productDeletePage,
         name='productDelete'),

    # package Management
    path('packageManagement/packages',
         views.packageManagement,
         name='packageManagement'),
    path('packageManagement/package/add/',
         views.packageAddPage,
         name='packageAdd'),
    path('packageManagement/package/<int:pk>',
         views.packageUpdatePage,
         name='packageUpdate'),

    # finance Management
    path('finance/invoices', views.invoiceManagement,
         name='invoiceManagement'),
    path('finance/invoice/<int:pk>', views.invoiceDetail,
         name='invoiceDetail'),
    path('finance/invoice/delete/<int:pk>', views.invoiceDeletePage,
         name='invoiceDeletePage'),

    # Equipment management
    path('equipmentManagement/equipments',
         views.equipmentManagement,
         name='equipmentManagement'),
    path('equipmentManagement/equipment/add/',
         views.equipmentAddPage,
         name='equipmentAdd'),
    path('equipmentManagement/equipment/<int:pk>',
         views.equipmentUpdatePage,
         name='equipmentUpdate'),
    path('equipmentManagement/equipment/delete/<int:pk>',
         views.equipmentDeletePage,
         name='equipmentDeletePage'),


    # Equipment maintanence
    path('equipmentMaintanence/equipments',
         views.equipmentMaintanence,
         name='equipmentMaintanence'),
    path('equipmentMaintanence/equipment/add/',
         views.equipmentMaintanenceAddPage,
         name='equipmentMaintanenceAdd'),
    path('equipmentMaintanence/equipment/<int:pk>',
         views.equipmentMaintanenceUpdatePage,
         name='equipmentMaintanenceUpdate'),
    path('equipmentMaintanence/equipment/delete/<int:pk>',
         views.equipmentMaintanenceDeletePage,
         name='equipmentMaintanenceDeletePage'),
]

tripod/core/urls.py
from django.urls import path

from core import views

app_name = 'core'

urlpatterns = [
    # account pages urls
    #  path('', views.home, name='home'),
    path('account/<int:pk>', views.updateUserProfile, name='updateProfile'),
    path('account/change_password',
         views.changePassword,
         name='changePassword'),
    path('account/login/', views.loginPage, name='login'),
    path('account/logout/', views.logoutPage, name='logout'),

    # customer portal
    path('portal/', views.customerHome, name='customerHome'),

    # jobs
    path('portal/jobRequests/', views.jobRequests, name='jobRequests'),
    path('portal/jobRequests/add/', views.jobReqAddPage, name='jobReqAdd'),
    path('portal/jobs/', views.jobsConfirmed, name='jobs'),
    path('portal/declinedJobs/', views.jobsDeclined, name='declinedJobs'),
    path('portal/job/<int:pk>', views.jobPage, name='jobPage'),
    path('portal/updateJob/<int:pk>', views.jobUpdate, name='jobUpdate'),
    path('portal/updatePackage/<int:pk>',
         views.jobUpdatePackage,
         name='jobUpdatePackage'),
    path('portal/taskComplete/<int:pk>',
         views.completeTask,
         name='completeTask'),
    path('portal/job/contract/<int:pk>',
         views.contractPage,
         name='jobContract'),
    path('portal/job/invoice/<int:pk>', views.invoicePage, name='jobInvoice'),
    path('portal/job/quest/<int:pk>',
         views.updateQuestForm,
         name='updateQuestForm'),
]

tripod/job/urls.py
from django.urls import path

from job import views

app_name = 'job'

urlpatterns = [
    path('', views.staffJobHomePage, name='staffJob'),

    # job request management
    path('jobReqManagement',
         views.jobReqManagementPage,
         name='jobReqManagementPage'),
    path('jobReqManagement/jobReq/add/', views.jobReqAddPage,
         name='jobReqAdd'),
    path('jobReqManagement/reqToJob/<int:pk>/',
         views.jobChangeReqToJob,
         name='jobChangeReqToJobPage'),
    path('jobReqManagement/deleteJob/<int:pk>/',
         views.deleteJob,
         name='delRequestJob'),

    # job management
    path('jobManagement', views.jobManagementPage, name='jobManagementPage'),
    path('completedJobManagement',
         views.completedJobManagementPage,
         name='completedJobManagementPage'),
    path('jobManagement/job/<int:pk>', views.jobPage, name='jobPage'),
    path('jobManagement/jobUpdate/<int:pk>/',
         views.jobUpdateJob,
         name='jobUpdateJob'),
    path('jobManagement/taskProcess/<int:pk>',
         views.processTask,
         name='processTask'),
    path('jobManagement/deleteJob/<int:pk>/',
         views.deleteJob,
         name='deleteJob'),
    path('jobManagement/taskEmailProcessWithoutSending/<int:pk>',
         views.processEmailTaskWithoutSendingEmail,
         name='processEmailTaskWithoutSending'),
    path('jobManagement/taskComplete/<int:pk>',
         views.completeTask,
         name='completeTask'),
    # invoice
    path('jobManagement/jobUpdate/<int:pk>/invoice',
         views.updateInvoice,
         name='jobUpdateInvoice'),
    path('jobManagement/job/<int:pk>/invoice',
         views.invoicePage,
         name='invoicePage'),
    path('jobManagement/job/<int:pk>/PayHistory/',
         views.addPayHistoryPage,
         name='addPayHistoryPage'),
    path('jobManagement/job/<int:pk>/updatePayHistory/',
         views.updatePayHistoryPage,
         name='updatePayHistoryPage'),
    path('jobManagement/job/<int:pk>/receipt',
         views.downloadInvoice,
         name='downloadInvoice'),

    # quest
    path('jobManagement/job/<int:pk>/questonniare',
         views.questPage,
         name='questPage'),

    # job declined management
    path('jobDecManagement',
         views.jobDecManagementPage,
         name='jobDecManagementPage'),
    path('jobDecManagement/jobDecline/<int:pk>',
         views.declineJob,
         name='declineJob'),
    path('jobDecManagement/jobConfirm/<int:pk>',
         views.confirmDeclinedJob,
         name='confirmDeclinedJob'),
    # appointment management
    path('taskManagement/app/<int:pk>', views.appointmentPage, name='appPage'),
]

tripod/settings/urls.py
from django.urls import path

from settings import views

app_name = 'settings'

urlpatterns = [
    # company pages urls
    path('', views.staffSettingsPage, name='staffSettings'),

    # workflow Management
    path(
        'workflowManagement',
        views.workflowManagement, name='workflowManagement'),
    path(
        'workflowManagement/workflow/<int:pk>',
        views.workflowUpdatePage, name='workflowUpdatePage'),
    path(
        'workflowManagement/workflow/add/',
        views.workflowAddPage, name='workflowAdd'),

    # work Templates management
    path(
        'workTemplateManagement',
        views.workTemplateManagement, name='workTemplateManagement'),
    path(
        'workTemplateManagement/workTemplate/<int:pk>',
        views.workTemplateUpdatePage, name='workTemplateUpdatePage'),
    path(
        'workTemplateManagement/workTemplate/add/',
        views.workTemplateAddPage, name='workTemplateAdd'),

    # email template management
    path(
        'emailTemplateManagement',
        views.emailTemplateManagement, name='emailTemplateManagement'),
    path(
        'emailTemplateManagement/emailTemplate/<int:pk>',
        views.emailTemplateUpdatePage, name='emailTemplateUpdatePage'),
    path(
        'emailTemplateManagement/emailTemplate/add/',
        views.emailTemplateAddPage, name='emailTemplateAdd'),

    # Contract template management
    path(
        'contractTemplateManagement',
        views.contractTemplateManagement, name='contractTemplateManagement'),
    path(
        'contractTemplateManagement/contractTemplate/<int:pk>',
        views.contractTemplateUpdatePage, name='contractTemplateUpdatePage'),
    path(
        'contractTemplateManagement/contractTemplate/add/',
        views.contractTemplateAddPage, name='contractTemplateAdd'),

    # Questionnaire template management
    path(
        'questTemplateManagement',
        views.questTemplateManagement, name='questTemplateManagement'),
    path(
        'questTemplateManagement/questTemplate/<int:pk>',
        views.questTemplateUpdatePage, name='questTemplateUpdatePage'),
    path(
        'questTemplateManagement/questTemplate/add/',
        views.questTemplateAddPage, name='questTemplateAdd'),
    # sources management
]

tripod/tripod/urls.py
from django.contrib import admin
from django.urls import path, include

from tripod.views import not_available_404, permission_error, admin_page
from tripod import settings

from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('error', not_available_404, name="error"),
    path('permission_error', permission_error, name="permission_error"),
    path('', include('core.urls')),
    path('blog/', include('blog.urls')),
    path('tripod-admin/', admin_page, name='adminPage'),
    path('tripod-admin/dashboard/', include('dashboard.urls')),
    path('tripod-admin/company/', include('company.urls')),
    path('tripod-admin/job/', include('job.urls')),
    path('tripod-admin/settings/', include('settings.urls')),
    # path('tripod-admin/...', include('settings.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tripod/tripod/views.py
from django.shortcuts import render


def not_available_404(request):
    return render(request, '404.html')


def permission_error(request):
    return render(request, 'permissionError.html')


def admin_page(request):
    user = request.user
    context = {'user': user}
    return render(request, 'admin_page.html', context)

tripod/tripod/templates/admin_base.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    {% block css_page %}{% endblock css_page %}
  </head>

<style media="screen">
  .content {
    display: grid;
    grid-template-columns: 1fr 9fr;
  }
  .sidebar {
    background-color: "rgba(231, 231, 231, 1)";

  main {
    display: flex;
    flex-wrap: nowrap;
    height: -webkit-fill-available;
    overflow-x: auto;
    overflow-y: hidden;
  }

  .bi {
    vertical-align: -.125em;
    pointer-events: none;
    fill: currentColor;
  }


</style>


  <body style="height: 100%;">

      <div class="">
        {% if request.user.is_superuser %}
          {% include 'admin_navbar.html' %}
        {% elif request.user.is_staff %}
          {% include 'staff_navbar.html' %}
        {% endif %}
      </div>
      {% include 'messages.html' %}
    <main>
      <div class="container-fluid">
        <div class="content">
          <div class="sidebar d-flex flex-column flex-shrink-0 p-1 bg-light" style="width: 200px;">
            <!-- <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none"> -->
              <!-- <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg> -->
              <!-- <span class="fs-4">Sidebar</span> -->
            <!-- </a> -->
            <!-- <hr> -->
            {% block sidebar %} {% endblock sidebar %}
            <!-- <hr> -->
          </div>
          <div class="row" style="margin:10px">
            {% block content %} {% endblock content %}
          </div>
        </div>
      </div>
    </main>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

tripod/tripod/templates/admin_guest_nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'adminPage' %}">TRIPOD</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:features' %}">Features</a>
        </li>
      </ul>
    </div>

    <ul class="navbar-nav mx-right">
      <li class="nav-item">
        {% if user.is_authenticated %}
        <a class="nav-link" href="{% url 'company:staffLogout' %}">Logout</a>
        {% else %}
        <a class="nav-link" href="{% url 'company:staffLogin' %}">Login</a>
        {% endif %}
      </li>
    </ul>

  </div>
</nav>

tripod/tripod/templates/admin_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'adminPage' %}">TRIPOD</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        {% comment %} <li class="nav-item"> {% endcomment %}
          {% comment %} <a class="nav-link active" aria-current="page" href="{% url 'company:home' %}">Home</a> {% endcomment %}
        {% comment %} </li> {% endcomment %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'dashboard:dashboardHome' %}">Dashboard</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'job:staffJob' %}">Jobs</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'company:staffCompany' %}">Company</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'settings:staffSettings' %}">Settings</a>
        </li>
      </ul>
    </div>

    <ul class="navbar-nav mx-right">
      {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'company:updateProfile' %}">Account</a>
        </li>
        <li>
          <a class="nav-link" href="{% url 'company:staffLogout' %}">Logout</a>
        </li>
        {% else %}
        <li>
          <a class="nav-link" href="{% url 'company:staffLogin' %}">Login</a>
        </li>
        {% endif %}
      </li>
    </ul>

  </div>
</nav>

tripod/tripod/templates/admin_page.html
{% extends 'admin_base_without_nav.html' %}

{% block sidebar %}
{% include 'sidebars/job_sidebar.html' %}
{% endblock sidebar %}

{% block content %}
<div class="row" style="padding:10px">
  <div class="col-3">
  </div>
  <div class="col-3">
    <div clas="card">
      <div class="card-body" style="text-align: right">
        <br>
        <br>
        <br>
        <h3 class="display-3">
          Welcome to Tripod Admin
        </h3>
        <small class="text-left"><i>Only for staffs, use the credentials provided by Business Admin</i></small>
        <br><br>
        {% if not user.is_authenticated %}
          <a class="btn btn-outline-primary btn-lg" class="link-primary" href="{% url 'company:staffLogin' %}">Login here</a></i>
        {% else %}
          <h5>Hi, {{ user.first_name }} 👋</h5>
        {% endif %}
      <br><br><br><br>
      <small>powered by TriPod</small><br>
      <small>Email address - daniel.abhishek@gmail.com</small><br>
      <small>Daniel Abhishek - Kandy</small>
      </div>
    </div>
  </div>
  {% if user.is_authenticated %}
    <div class="col-6">
      <div class="row">
        <div class="col-6">
        <br><br><br><br>
          <div class="card">
            <div class="card-body">
              <h4 class="card-title">
                <a class="nav-link link-secondary" href="{% url 'dashboard:dashboardHome'%}">🗠 Dashboard</a>
              </h4>
            </div>
          </div>
          <br>
          <div class="card">
            <div class="card-body">
              <h4 class="card-title">
                <a class="nav-link link-secondary" href="{% url 'job:staffJob'%}">📷 Jobs</a>
              </h4>
            </div>
          </div>
          <br>
          <div class="card">
            <div class="card-body">
              <h4 class="card-title">
                <a class="nav-link link-secondary" href="{% url 'company:staffCompany'%}">🏢 Company</a>
              </h4>
            </div>
          </div>
          <br>
          <div class="card">
            <div class="card-body">
              <h4 class="card-title">
                <a class="nav-link link-secondary" href="{% url 'settings:staffSettings'%}">🔧 Settings</a>
              </h4>
            </div>
          </div>

        </div>
      </div>
    </div> 
  {% endif %}
</div> 

{% endblock content %}

tripod/tripod/templates/customer_navbar.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}{% endblock title %}</title> 
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    {% block css_page %}{% endblock css_page %}
  </head>
  <body>
<!-- Navbar component -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'core:customerHome' %}">TRIPOD</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            {% comment %} <li class="nav-item"> {% endcomment %}
              {% comment %} <a class="nav-link active" aria-current="page" href="{% url 'core:home' %}">Home</a> {% endcomment %}
            {% comment %} </li> {% endcomment %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:tripodPage' %}">Blog</a>
            </li>
          </ul>
        </div>
        
        <ul class="navbar-nav mx-right">

          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'core:updateProfile' request.user.id %}">Account</a>
            </li>
            <li>
              <a class="nav-link" href="{% url 'core:logout' %}">Logout</a>
            </li>
            {% else %}
            <li>
              <a class="nav-link" href="{% url 'core:login' %}">Login</a>
            </li>
            {% endif %}
        </ul>
        
      </div>
    </nav>
<!-- End of Navbar component -->
    <div class="container-fluid">
      {% block content %} {% endblock content %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

tripod/tripod/templates/guest_navbar.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}{% endblock title %}</title> 
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    {% block css_page %}{% endblock css_page %}
  </head>
  <body>
<!-- Navbar component -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'blog:tripodPage' %}">TRIPOD</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            {% comment %} <li class="nav-item"> {% endcomment %}
              {% comment %} <a class="nav-link active" aria-current="page" href="{% url 'core:home' %}">Home</a> {% endcomment %}
            {% comment %} </li> {% endcomment %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:features' %}">Features</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:contactUs' %}">Contact Us</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'core:customerHome' %}">Customer Portal</a>
            </li>
          </ul>
        </div>
        
        <ul class="navbar-nav mx-right">
          <li class="nav-item">
            {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'core:logout' %}">Logout</a>
            {% else %}
            <a class="nav-link" href="{% url 'core:login' %}">Login</a>
            {% endif %}
          </li>
        </ul>
        
      </div>
    </nav>
<!-- End of Navbar component -->
    <div class="container-fluid">
      {% block content %} {% endblock content %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

tripod/tripod/templates/permissionError.html
<h1>Permission Denied, please contact admin</h1>

tripod/tripod/templates/staff_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'adminPage' %}">TRIPOD</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        {% comment %} <li class="nav-item"> {% endcomment %}
          {% comment %} <a class="nav-link active" aria-current="page" href="{% url 'company:home' %}">Home</a> {% endcomment %}
        {% comment %} </li> {% endcomment %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'dashboard:dashboardHome' %}">Dashboard</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'job:staffJob' %}">Jobs</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'company:staffCompany' %}">Company</a>
        </li>
      </ul>
    </div>

    <ul class="navbar-nav mx-right">
      <li class="nav-item">
        {% if user.is_authenticated %}
         <li class="nav-item">
          <a class="nav-link" href="{% url 'company:updateProfile' %}">Account</a>
        </li>

        <a class="nav-link" href="{% url 'company:staffLogout' %}">Logout</a>
        {% else %}
        <a class="nav-link" href="{% url 'company:staffLogin' %}">Login</a>
        {% endif %}
      </li>
    </ul>

  </div>
</nav>