tripod/job/urls.py
from django.urls import path

from job import views

app_name = 'job'

urlpatterns = [
    path('', views.staffJobHomePage, name='staffJob'),

    # job request management
    path('jobReqManagement',
         views.jobReqManagementPage,
         name='jobReqManagementPage'),
    path('jobReqManagement/jobReq/add/', views.jobReqAddPage,
         name='jobReqAdd'),
    path('jobReqManagement/reqToJob/<int:pk>/',
         views.jobChangeReqToJob,
         name='jobChangeReqToJobPage'),
    path('jobReqManagement/deleteJob/<int:pk>/',
         views.deleteJob,
         name='delRequestJob'),

    # job management
    path('jobManagement', views.jobManagementPage, name='jobManagementPage'),
    path('completedJobManagement',
         views.completedJobManagementPage,
         name='completedJobManagementPage'),
    path('jobManagement/job/<int:pk>', views.jobPage, name='jobPage'),
    path('jobManagement/jobUpdate/<int:pk>/',
         views.jobUpdateJob,
         name='jobUpdateJob'),
    path('jobManagement/taskProcess/<int:pk>',
         views.processTask,
         name='processTask'),
    path('jobManagement/deleteJob/<int:pk>/',
         views.deleteJob,
         name='deleteJob'),
    path('jobManagement/taskEmailProcessWithoutSending/<int:pk>',
         views.processEmailTaskWithoutSendingEmail,
         name='processEmailTaskWithoutSending'),
    path('jobManagement/taskComplete/<int:pk>',
         views.completeTask,
         name='completeTask'),
    # invoice
    path('jobManagement/jobUpdate/<int:pk>/invoice',
         views.updateInvoice,
         name='jobUpdateInvoice'),
    path('jobManagement/job/<int:pk>/invoice',
         views.invoicePage,
         name='invoicePage'),
    path('jobManagement/job/<int:pk>/PayHistory/',
         views.addPayHistoryPage,
         name='addPayHistoryPage'),
    path('jobManagement/job/<int:pk>/updatePayHistory/',
         views.updatePayHistoryPage,
         name='updatePayHistoryPage'),
    path('jobManagement/job/<int:pk>/receipt',
         views.downloadInvoice,
         name='downloadInvoice'),

    # quest
    path('jobManagement/job/<int:pk>/questonniare',
         views.questPage,
         name='questPage'),

    # job declined management
    path('jobDecManagement',
         views.jobDecManagementPage,
         name='jobDecManagementPage'),
    path('jobDecManagement/jobDecline/<int:pk>',
         views.declineJob,
         name='declineJob'),
    path('jobDecManagement/jobConfirm/<int:pk>',
         views.confirmDeclinedJob,
         name='confirmDeclinedJob'),
    # appointment management
    path('taskManagement/app/<int:pk>', views.appointmentPage, name='appPage'),
]

tripod/settings/urls.py
from django.urls import path

from settings import views

app_name = 'settings'

urlpatterns = [
    # company pages urls
    path('', views.staffSettingsPage, name='staffSettings'),

    # workflow Management
    path(
        'workflowManagement',
        views.workflowManagement, name='workflowManagement'),
    path(
        'workflowManagement/workflow/<int:pk>',
        views.workflowUpdatePage, name='workflowUpdatePage'),
    path(
        'workflowManagement/workflow/add/',
        views.workflowAddPage, name='workflowAdd'),

    # work Templates management
    path(
        'workTemplateManagement',
        views.workTemplateManagement, name='workTemplateManagement'),
    path(
        'workTemplateManagement/workTemplate/<int:pk>',
        views.workTemplateUpdatePage, name='workTemplateUpdatePage'),
    path(
        'workTemplateManagement/workTemplate/add/',
        views.workTemplateAddPage, name='workTemplateAdd'),

    # email template management
    path(
        'emailTemplateManagement',
        views.emailTemplateManagement, name='emailTemplateManagement'),
    path(
        'emailTemplateManagement/emailTemplate/<int:pk>',
        views.emailTemplateUpdatePage, name='emailTemplateUpdatePage'),
    path(
        'emailTemplateManagement/emailTemplate/add/',
        views.emailTemplateAddPage, name='emailTemplateAdd'),

    # Contract template management
    path(
        'contractTemplateManagement',
        views.contractTemplateManagement, name='contractTemplateManagement'),
    path(
        'contractTemplateManagement/contractTemplate/<int:pk>',
        views.contractTemplateUpdatePage, name='contractTemplateUpdatePage'),
    path(
        'contractTemplateManagement/contractTemplate/add/',
        views.contractTemplateAddPage, name='contractTemplateAdd'),

    # Questionnaire template management
    path(
        'questTemplateManagement',
        views.questTemplateManagement, name='questTemplateManagement'),
    path(
        'questTemplateManagement/questTemplate/<int:pk>',
        views.questTemplateUpdatePage, name='questTemplateUpdatePage'),
    path(
        'questTemplateManagement/questTemplate/add/',
        views.questTemplateAddPage, name='questTemplateAdd'),
    # sources management
]

tripod/tripod/urls.py
from django.contrib import admin
from django.urls import path, include

from tripod.views import not_available_404, permission_error, admin_page
from tripod import settings

from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('error', not_available_404, name="error"),
    path('permission_error', permission_error, name="permission_error"),
    path('', include('core.urls')),
    path('blog/', include('blog.urls')),
    path('tripod-admin/', admin_page, name='adminPage'),
    path('tripod-admin/dashboard/', include('dashboard.urls')),
    path('tripod-admin/company/', include('company.urls')),
    path('tripod-admin/job/', include('job.urls')),
    path('tripod-admin/settings/', include('settings.urls')),
    # path('tripod-admin/...', include('settings.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tripod/settings/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import redirect, render
from django.contrib import messages

from settings.models import (Workflow, EmailTemplate, ContractTemplate,
                             QuestionnaireTemplate, Source, WorkTemplate)
from settings.forms import (WorkflowForm, WorkTemplateForm, EmailTemplateForm,
                            ContractTemplateForm, QuestionnaireTemplateForm)

from tripod.utils import superuser_check


@login_required(login_url='company:staffLogin')
@user_passes_test(superuser_check, login_url="permission_error")
def staffSettingsPage(request):
    """
    Settings homepage which is only visible to admin logins,
    Where the main application content will be available
    """
    return render(request, 'admin/settings.html')


@login_required(login_url='company:staffLogin')
@user_passes_test(superuser_check, login_url="permission_error")
def workflowManagement(request):
    """
    workflow management page, where you can define the workflow
    which will be linked to workflow automation for job creation
    """
    workflows = Workflow.objects.all()
    context = {'workflows': workflows}

    return render(request, 'workflowManagement/workflowManagement.html',
                  context)


@login_required(login_url='company:staffLogin')
@user_passes_test(superuser_check, login_url="permission_error")
def workflowUpdatePage(request, pk):
    """
    updating the workflow item
    """
    workflow = Workflow.objects.get(pk=pk)
    form = WorkflowForm(instance=workflow, userObj=None, operation=None)

    if request.method == "POST":
        form = WorkflowForm(request.POST,
                            instance=workflow,
                            userObj=request.user,
                            operation='updating')
        if form.is_valid():
            obj = form.save()
            messages.success(request, f'Workflow {obj} successfully updated')
            return redirect('settings:workflowManagement')
        else:
            messages.error(request, 'Invalid form submission')

    context = {'form': form, 'workflow': workflow}
    return render(request, 'workflowManagement/workflow.html', context)


@login_required(login_url='company:staffLogin')
@user_passes_test(superuser_check, login_url="permission_error")
def workflowAddPage(request):
    """
    Adding new workflow
    """
    form = WorkflowForm(userObj=None, operation=None)
    if request.method == "POST":
        form = WorkflowForm(request.POST,
                            userObj=request.user,
                            operation='creating')
        if form.is_valid():
            obj = form.save()
            messages.success(request, f'Workflow {obj} successfully added')
            return redirect('settings:workflowManagement')
        else:
            messages.error(request, 'Invalid form submission')

    context = {'form': form}
    return render(request, 'workflowManagement/workflowAdd.html', context)


@login_required(login_url='company:staffLogin')
@user_passes_test(superuser_check, login_url="permission_error")
def workTemplateManagement(request):
    """
    work Template management page, where you can define the work template
    that is responsible for work creation
    """
    workTemplates = WorkTemplate.objects.all()
    context = {'workTemplates': workTemplates}

    return render(request, 'workflowManagement/workTemplateManagement.html',
                  context)


@login_required(login_url='company:staffLogin')
@user_passes_test(superuser_check, login_url="permission_error")
def workTemplateUpdatePage(request, pk):
    """
    updating the work template
    """
    work_template = WorkTemplate.objects.get(pk=pk)
    form = WorkTemplateForm(instance=work_template)

    if request.method == "POST":
        form = WorkTemplateForm(request.POST, instance=work_template)
        if form.is_valid():
            obj = form.save()
            messages.success(request,
                             f'Work Template {obj} successfully updated')
            return redirect('settings:workTemplateManagement')
        else:
            messages.error(request, 'Invalid form submission')

    context = {'form': form, 'workTemplate': work_template}
    return render(request, 'workflowManagement/workTemplate.html', context)


@login_required(login_url='company:staffLogin')
@user_passes_test(superuser_check, login_url="permission_error")
def workTemplateAddPage(request):
    """
    Adding new work template
    """
    form = WorkTemplateForm()
    if request.method == "POST":
        form = WorkTemplateForm(request.POST)
        if form.is_valid():
            obj = form.save()
            messages.success(request, f'Workflow {obj} successfully added')
            return redirect('settings:workTemplateManagement')
        else:
            messages.error(request, 'Invalid form submission')

    context = {'form': form}
    return render(request, 'workflowManagement/workTemplateAdd.html', context)


@login_required(login_url='company:staffLogin')
@user_passes_test(superuser_check, login_url="permission_error")
def emailTemplateManagement(request):
    """
    email Template management page, where you can define the email template
    that is responsible for email template creation
    """
    emailTemplates = EmailTemplate.objects.all()
    context = {'emailTemplates': emailTemplates}

    return render(request, 'templateManagement/emailTemplateManagement.html',
                  context)


@login_required(login_url='company:staffLogin')
@user_passes_test(superuser_check, login_url="permission_error")
def emailTemplateUpdatePage(request, pk):
    """
    updating the email template
    """
    email_template = EmailTemplate.objects.get(pk=pk)
    form = EmailTemplateForm(instance=email_template,
                             userObj=None,
                             operation=None)

    if request.method == "POST":
        form = EmailTemplateForm(request.POST,
                                 instance=email_template,
                                 userObj=request.user,
                                 operation='updating')
        if form.is_valid():
            obj = form.save()
            messages.success(request,
                             f'Email Template {obj} successfully updated')
            return redirect('settings:emailTemplateManagement')
        else:
            messages.error(request, 'Invalid form submission')

    context = {'form': form, 'emailTemplate': email_template}
    return render(request, 'templateManagement/emailTemplate.html', context)


@login_required(login_url='company:staffLogin')
@user_passes_test(superuser_check, login_url="permission_error")
def emailTemplateAddPage(request):
    """
    Adding new work template
    """
    form = EmailTemplateForm(userObj=None, operation=None)
    if request.method == "POST":
        form = EmailTemplateForm(request.POST,
                                 userObj=request.user,
                                 operation='creating')
        if form.is_valid():
            obj = form.save()
            messages.success(request,
                             f'Email Template {obj} successfully updated')
            return redirect('settings:emailTemplateManagement')
        else:
            messages.error(request, 'Invalid form submission')

    context = {'form': form}
    return render(request, 'templateManagement/emailTemplateAdd.html', context)


@login_required(login_url='company:staffLogin')
@user_passes_test(superuser_check, login_url="permission_error")
def contractTemplateManagement(request):
    """
    contract Template management page, where you can define the contract
    template that is responsible for contract template creation
    """
    contractTemplates = ContractTemplate.objects.all()
    context = {'contractTemplates': contractTemplates}

    return render(request,
                  'templateManagement/contractTemplateManagement.html',
                  context)


@login_required(login_url='company:staffLogin')
@user_passes_test(superuser_check, login_url="permission_error")
def contractTemplateUpdatePage(request, pk):
    """
    updating the contract template
    """
    contract_template = ContractTemplate.objects.get(pk=pk)
    form = ContractTemplateForm(instance=contract_template,
                                userObj=None,
                                operation=None)

    if request.method == "POST":
        form = ContractTemplateForm(request.POST,
                                    instance=contract_template,
                                    userObj=request.user,
                                    operation='updating')
        if form.is_valid():
            obj = form.save()
            messages.success(request,
                             f'Contract Template {obj} successfully updated')
            return redirect('settings:contractTemplateManagement')
        else:
            messages.error(request, 'Invalid form submission')

    context = {'form': form, 'contractTemplate': contract_template}
    return render(request, 'templateManagement/contractTemplate.html', context)


@login_required(login_url='company:staffLogin')
@user_passes_test(superuser_check, login_url="permission_error")
def contractTemplateAddPage(request):
    """
    Adding new work template
    """
    form = ContractTemplateForm(userObj=None, operation=None)
    if request.method == "POST":
        form = ContractTemplateForm(request.POST,
                                    userObj=request.user,
                                    operation='creating')
        if form.is_valid():
            obj = form.save()
            messages.success(request,
                             f'Contract Template {obj} successfully created')
            return redirect('settings:contractTemplateManagement')
        else:

tripod/settings/templates/templateManagement/contractTemplate.html
{% extends 'admin_base_without_nav.html' %}
{% load crispy_forms_tags %}


{% block content %}
    <h2>Contract Template - {{ contractTemplate.template_name }}</h2>

    <form method="POST" action="">
      {% csrf_token %}
      <br>
      <div class="row">
        <div class="col">
          {{ form.template_name | as_crispy_field }}
          {{ form.subject | as_crispy_field }}
          {{ form.body | as_crispy_field }}
          {{ form.thank_you | as_crispy_field }}
          {{ form.signature | as_crispy_field }}
        </div>
      </div>
      <br>
      <input class="btn btn-primary" type="submit" value="Update contract template">
    </form>
{% endblock %}

tripod/settings/templates/templateManagement/contractTemplateAdd.html
{% extends 'admin_base_without_nav.html' %}
{% load crispy_forms_tags %}


{% block content %}
    <h2>Create New contract Template</h2>

    <form method="POST" action="">
      {% csrf_token %}
      {{ form.template_name | as_crispy_field }}
      {{ form.subject | as_crispy_field }}
      {{ form.body | as_crispy_field }}
      {{ form.thank_you | as_crispy_field }}
      {{ form.signature | as_crispy_field }}
      <br>
      <input class="btn btn-primary" type="submit" value="Create Contract Template">
    </form>
{% endblock %}

tripod/settings/templates/templateManagement/contractTemplateManagement.html
{% extends 'admin_base.html' %}

{% block sidebar %}
{% include 'sidebars/settings_sidebar.html' %}
{% endblock sidebar %}

{% block content %}


<div class="col">
  <div class="">
    <section class="jumbotron text-left">
      <h1 class="jumbotron-heading">Comtract Template Management</h1>
      <!-- <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p> -->
      <p>
        <a class="btn btn-outline-primary" href="{% url 'settings:contractTemplateAdd' %}">Add new contract Template</a>
        <a href="#" class="btn btn-secondary my-2">Search</a>
      </p>
    </section>
    <hr>

    <h6 class="text-muted">List of Contract Templates</h6>
    <table class="table text-left align-middle">
      <thead class="thead-light">
        <tr>
          <th>Name</th>
        </tr>
      </thead>
      <tbody>
        {% for contractTemplate in contractTemplates %}
          <tr>
            <th><a class="nav-link" href="{% url 'settings:contractTemplateUpdatePage' contractTemplate.id %}">{{ contractTemplate.template_name }}</a></th>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock content %}

tripod/settings/templates/templateManagement/emailTemplate.html
{% extends 'admin_base_without_nav.html' %}
{% load crispy_forms_tags %}


{% block content %}
    <h2>Email Template - {{ emailTemplate.name }}</h2>

    <form method="POST" action="">
      {% csrf_token %}
      <br>
      <div class="row">
        <div class="col">
          {{ form.workflow | as_crispy_field }}
          {{ form.template_name | as_crispy_field }}
          {{ form.subject | as_crispy_field }}
          {{ form.body | as_crispy_field }}
          {{ form.thank_you | as_crispy_field }}
        </div>
      </div>
      <br>
      <input class="btn btn-primary" type="submit" value="Update email template">
    </form>
{% endblock %}

tripod/settings/templates/templateManagement/emailTemplateAdd.html
{% extends 'admin_base_without_nav.html' %}
{% load crispy_forms_tags %}


{% block content %}
    <h2>Create New Email Template</h2>

    <form method="POST" action="">
      {% csrf_token %}
      {{ form.workflow | as_crispy_field }}
      {{ form.template_name | as_crispy_field }}
      {{ form.subject | as_crispy_field }}
      {{ form.body | as_crispy_field }}
      {{ form.thank_you | as_crispy_field }}
      <br>
      <input class="btn btn-primary" type="submit" value="Create Email Template">
    </form>
{% endblock %}

tripod/settings/templates/templateManagement/emailTemplateManagement.html
{% extends 'admin_base.html' %}

{% block sidebar %}
{% include 'sidebars/settings_sidebar.html' %}
{% endblock sidebar %}

{% block content %}


<div class="col">
  <div class="">
    <section class="jumbotron text-left">
      <h1 class="jumbotron-heading">Email Template Management</h1>
      <!-- <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p> -->
      <p>
        <a class="btn btn-outline-primary" href="{% url 'settings:emailTemplateAdd' %}">Add new email Template</a>
        <a href="#" class="btn btn-secondary my-2">Search</a>
      </p>
    </section>
    <hr>

    <h6 class="text-muted">List of Email Templates</h6>
    <table class="table text-left align-middle">
      <thead class="thead-light">
        <tr>
          <th>Workflow</th>
          <th>Name</th>
        </tr>
      </thead>
      <tbody>
        {% for emailTemplate in emailTemplates %}
          <tr>
            <th>{{ emailTemplate.workflow }}</th>
            <th><a class="nav-link" href="{% url 'settings:emailTemplateUpdatePage' emailTemplate.id %}">{{ emailTemplate.template_name }}</a></th>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock content %}

tripod/settings/templates/templateManagement/questTemplate.html
{% extends 'admin_base_without_nav.html' %}
{% load crispy_forms_tags %}


{% block content %}
    <h2>Questionnaire Template - {{ questTemplate.template_name }}</h2>

    <form method="POST" action="">
      {% csrf_token %}
      <br>
      <div class="row">
        <div class="col">
          {{ form.template_name | as_crispy_field }}
          {{ form.subject | as_crispy_field }}
          {{ form.body | as_crispy_field }}
          {{ form.question_one | as_crispy_field }}
          {{ form.question_two | as_crispy_field }}
          {{ form.question_three | as_crispy_field }}
          {{ form.question_four | as_crispy_field }}
          {{ form.question_five | as_crispy_field }}
        </div>
      </div>
      <br>
      <input class="btn btn-primary" type="submit" value="Update questionnaire template">
    </form>
{% endblock %}

tripod/settings/templates/templateManagement/questTemplateAdd.html
{% extends 'admin_base_without_nav.html' %}
{% load crispy_forms_tags %}


{% block content %}
    <h2>Create New Questionnaire Template</h2>

    <form method="POST" action="">
      {% csrf_token %}
      {{ form.template_name | as_crispy_field }}
      {{ form.subject | as_crispy_field }}
      {{ form.body | as_crispy_field }}
      {{ form.question_one | as_crispy_field }}
      {{ form.question_two | as_crispy_field }}
      {{ form.question_three | as_crispy_field }}
      {{ form.question_four | as_crispy_field }}
      {{ form.question_five | as_crispy_field }}
      <br>
      <input class="btn btn-primary" type="submit" value="Create Questionnaire Template">
    </form>
{% endblock %}

tripod/settings/templates/templateManagement/questTemplateManagement.html
{% extends 'admin_base.html' %}

{% block sidebar %}
{% include 'sidebars/settings_sidebar.html' %}
{% endblock sidebar %}

{% block content %}



<div class="col">
  <div class="">
    <section class="jumbotron text-left">
      <h1 class="jumbotron-heading">Questionnaire Template Management</h1>
      <!-- <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p> -->
      <p>
        <a class="btn btn-outline-primary" href="{% url 'settings:questTemplateAdd' %}">Add new Questionnaire Template</a>
        <a href="#" class="btn btn-secondary my-2">Search</a>
      </p>
    </section>
    <hr>

    <h6 class="text-muted">List of Questionnaire Templates</h6>
    <table class="table text-left align-middle">
      <thead class="thead-light">
        <tr>
          <th>Name</th>
        </tr>
      </thead>
      <tbody>
        {% for questTemplate in questTemplates %}
          <tr>
            <th><a class="nav-link" href="{% url 'settings:questTemplateUpdatePage' questTemplate.id %}">{{ questTemplate.template_name }}</a></th>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock content %}