tripod/company/urls.py
from django.urls import path

from company import views

app_name = 'company'

urlpatterns = [
    # company pages urls
    path('', views.staffCompanyHomePage, name='staffCompany'),
    path('login/', views.staffLoginPage, name='staffLogin'),
    path('logout/', views.staffLogoutPage, name='staffLogout'),
    path('<int:pk>', views.companyUpdate, name='companyUpdate'),
    path('account', views.updateProfile, name='updateProfile'),
    path('account/change_password',
         views.changePassword,
         name='changePassword'),
    # Employee management
    path('employeeManagement',
         views.employeeManagementPage,
         name='employeeManagement'),
    path('employeeManagement/employee/<int:pk>',
         views.staffUpdatePage,
         name='employeeUpdatePage'),
    path('clientManagement/employee/delete/<int:pk>',
         views.userDeletePage,
         name='employeeDeletePage'),
    path('employeeManagement/employee/add/',
         views.staffAddPage,
         name='employeeAdd'),

    # User management
    path('clientManagement',
         views.clientManagementPage,
         name='clientManagement'),
    path('clientManagement/client/<int:pk>',
         views.clientUpdatePage,
         name='clientUpdatePage'),
    path('clientManagement/client/delete/<int:pk>',
         views.userDeletePage,
         name='clientDeletePage'),
    path('clientManagement/client/add/', views.clientAddPage,
         name='clientAdd'),

    # Event management
    path('packageManagement/events',
         views.eventManagement,
         name='eventManagement'),
    path('packageManagement/event/add/', views.eventAddPage, name='eventAdd'),
    path('packageManagement/event/<int:pk>',
         views.eventUpdatePage,
         name='eventUpdate'),
    path('packageManagement/event/delete/<int:pk>',
         views.eventDeletePage,
         name='eventDelete'),

    # Product Management
    path('packageManagement/products',
         views.productManagement,
         name='productManagement'),
    path('packageManagement/product/add/',
         views.productAddPage,
         name='productAdd'),
    path('packageManagement/product/<int:pk>',
         views.productUpdatePage,
         name='productUpdate'),
    path('packageManagement/product/delete/<int:pk>',
         views.productDeletePage,
         name='productDelete'),

    # package Management
    path('packageManagement/packages',
         views.packageManagement,
         name='packageManagement'),
    path('packageManagement/package/add/',
         views.packageAddPage,
         name='packageAdd'),
    path('packageManagement/package/<int:pk>',
         views.packageUpdatePage,
         name='packageUpdate'),

    # finance Management
    path('finance/invoices', views.invoiceManagement,
         name='invoiceManagement'),
    path('finance/invoice/<int:pk>', views.invoiceDetail,
         name='invoiceDetail'),
    path('finance/invoice/delete/<int:pk>', views.invoiceDeletePage,
         name='invoiceDeletePage'),

    # Equipment management
    path('equipmentManagement/equipments',
         views.equipmentManagement,
         name='equipmentManagement'),
    path('equipmentManagement/equipment/add/',
         views.equipmentAddPage,
         name='equipmentAdd'),
    path('equipmentManagement/equipment/<int:pk>',
         views.equipmentUpdatePage,
         name='equipmentUpdate'),
    path('equipmentManagement/equipment/delete/<int:pk>',
         views.equipmentDeletePage,
         name='equipmentDeletePage'),


    # Equipment maintanence
    path('equipmentMaintanence/equipments',
         views.equipmentMaintanence,
         name='equipmentMaintanence'),
    path('equipmentMaintanence/equipment/add/',
         views.equipmentMaintanenceAddPage,
         name='equipmentMaintanenceAdd'),
    path('equipmentMaintanence/equipment/<int:pk>',
         views.equipmentMaintanenceUpdatePage,
         name='equipmentMaintanenceUpdate'),
    path('equipmentMaintanence/equipment/delete/<int:pk>',
         views.equipmentMaintanenceDeletePage,
         name='equipmentMaintanenceDeletePage'),
]

tripod/job/urls.py
from django.urls import path

from job import views

app_name = 'job'

urlpatterns = [
    path('', views.staffJobHomePage, name='staffJob'),

    # job request management
    path('jobReqManagement',
         views.jobReqManagementPage,
         name='jobReqManagementPage'),
    path('jobReqManagement/jobReq/add/', views.jobReqAddPage,
         name='jobReqAdd'),
    path('jobReqManagement/reqToJob/<int:pk>/',
         views.jobChangeReqToJob,
         name='jobChangeReqToJobPage'),
    path('jobReqManagement/deleteJob/<int:pk>/',
         views.deleteJob,
         name='delRequestJob'),

    # job management
    path('jobManagement', views.jobManagementPage, name='jobManagementPage'),
    path('completedJobManagement',
         views.completedJobManagementPage,
         name='completedJobManagementPage'),
    path('jobManagement/job/<int:pk>', views.jobPage, name='jobPage'),
    path('jobManagement/jobUpdate/<int:pk>/',
         views.jobUpdateJob,
         name='jobUpdateJob'),
    path('jobManagement/taskProcess/<int:pk>',
         views.processTask,
         name='processTask'),
    path('jobManagement/deleteJob/<int:pk>/',
         views.deleteJob,
         name='deleteJob'),
    path('jobManagement/taskEmailProcessWithoutSending/<int:pk>',
         views.processEmailTaskWithoutSendingEmail,
         name='processEmailTaskWithoutSending'),
    path('jobManagement/taskComplete/<int:pk>',
         views.completeTask,
         name='completeTask'),
    # invoice
    path('jobManagement/jobUpdate/<int:pk>/invoice',
         views.updateInvoice,
         name='jobUpdateInvoice'),
    path('jobManagement/job/<int:pk>/invoice',
         views.invoicePage,
         name='invoicePage'),
    path('jobManagement/job/<int:pk>/PayHistory/',
         views.addPayHistoryPage,
         name='addPayHistoryPage'),
    path('jobManagement/job/<int:pk>/updatePayHistory/',
         views.updatePayHistoryPage,
         name='updatePayHistoryPage'),
    path('jobManagement/job/<int:pk>/receipt',
         views.downloadInvoice,
         name='downloadInvoice'),

    # quest
    path('jobManagement/job/<int:pk>/questonniare',
         views.questPage,
         name='questPage'),

    # job declined management
    path('jobDecManagement',
         views.jobDecManagementPage,
         name='jobDecManagementPage'),
    path('jobDecManagement/jobDecline/<int:pk>',
         views.declineJob,
         name='declineJob'),
    path('jobDecManagement/jobConfirm/<int:pk>',
         views.confirmDeclinedJob,
         name='confirmDeclinedJob'),
    # appointment management
    path('taskManagement/app/<int:pk>', views.appointmentPage, name='appPage'),
]

tripod/tripod/urls.py
from django.contrib import admin
from django.urls import path, include

from tripod.views import not_available_404, permission_error, admin_page
from tripod import settings

from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('error', not_available_404, name="error"),
    path('permission_error', permission_error, name="permission_error"),
    path('', include('core.urls')),
    path('blog/', include('blog.urls')),
    path('tripod-admin/', admin_page, name='adminPage'),
    path('tripod-admin/dashboard/', include('dashboard.urls')),
    path('tripod-admin/company/', include('company.urls')),
    path('tripod-admin/job/', include('job.urls')),
    path('tripod-admin/settings/', include('settings.urls')),
    # path('tripod-admin/...', include('settings.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tripod/company/views.py
from django.contrib import messages
from django.shortcuts import redirect, render
from django.contrib.auth import (authenticate, login, logout, get_user_model,
                                 update_session_auth_hash)
from django.db import IntegrityError
from django.db.models import Q
from django.db.models.deletion import RestrictedError
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import login_required, user_passes_test
from django.forms.models import modelformset_factory
from django.core.exceptions import ObjectDoesNotExist

from core.forms import (AccountCreationForm, CustomUserChangeForm, CompanyForm,
                        StaffProfileUpdateForm)
from core.models import Company
from company.models import (Event, Product, Package, PackageLinkProduct,
                            Equipment, EquipmentMaintanence)
from company.forms import (EventForm, ProductForm, PackageForm,
                           PackageLinkProductAddForm, EquipmentForm,
                           EquipmentMaintanenceForm)
from company.utils import superuser_check, staff_check

from finance.models import Invoice, PaymentHistory

from tripod.utils import get_company, force_password_change_check


def staffLoginPage(request):
    """
    Seperate view function for staffs to login, with the given
    email and password
    """
    if request.user.is_authenticated and request.user.is_staff:
        messages.info(request, 'Already logged in')
        return redirect('company:staffCompany')
    else:
        company = get_company()
        if request.method == "POST":
            email = request.POST.get('email')
            password = request.POST.get('password')

            user = authenticate(request, email=email, password=password)

            if user is None:
                messages.error(request, 'Username or password incorrect')
            elif not user.is_staff:
                messages.error(request, 'Staffs only can access')
            elif user is not None and user.is_staff:
                login(request, user)
                messages.success(request, 'Successfully logged in')
                return redirect('adminPage')
            else:
                messages.error(request, 'Username or password incorrect')

        context = {'company': company}
        return render(request, 'staffs/login.html', context)


@login_required(login_url='company:staffLogin')
def staffLogoutPage(request):
    """
    Staffs Logout view function which redirects back to
    staffs home
    """
    logout(request)
    messages.success(request, 'Successfully logged out')
    return redirect('company:staffLogin')


@login_required(login_url='company:staffLogin')
@user_passes_test(force_password_change_check,
                  login_url="company:changePassword")
@user_passes_test(staff_check, login_url='permission_error')
def staffCompanyHomePage(request):
    """
    Company homepage which is only visible to admin logins,
    Where the main application content will be available
    """
    company = Company.objects.filter(active=True).first()
    context = {'company': company}
    return render(request, 'admin/company.html', context)


@login_required(login_url="company:staffLogin")
@user_passes_test(staff_check, login_url='permission_error')
def changePassword(request):
    """
    Changing password of the user who logged in
    """
    form = PasswordChangeForm(request.user)
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            user.force_password_change = False
            user.password_change_code = ''
            user.save()
            update_session_auth_hash(request, user)
            messages.success(request, "Your password was successfully updated")
            return redirect('company:staffCompany')
        else:
            messages.error(request, 'Invalid form submission')

    context = {'form': form}
    return render(request, 'staffs/change_password.html', context)


@login_required(login_url='company:staffLogin')
@user_passes_test(force_password_change_check,
                  login_url="company:changePassword")
@user_passes_test(staff_check, login_url="permission_error")
def updateProfile(request):
    """
    user profile updating
    """
    user = request.user
    form = StaffProfileUpdateForm(instance=user)

    if request.method == "POST":
        form = StaffProfileUpdateForm(request.POST or None, instance=user)

        if form.is_valid():
            user.email = form.cleaned_data['email']
            user.username = form.cleaned_data['username']
            user.first_name = form.cleaned_data['first_name']
            user.last_name = form.cleaned_data['last_name']
            user.gender = form.cleaned_data['gender']
            user.contact_number = form.cleaned_data['contact_number']
            user.contact_number_2 = form.cleaned_data['contact_number_2']
            user.address = form.cleaned_data['address']
            user.address_2 = form.cleaned_data['address_2']
            user.city = form.cleaned_data['city']
            user.province = form.cleaned_data['province']
            user.country = form.cleaned_data['country']
            user.save()
            messages.success(request, "Successfully update the profile")
            return redirect('company:staffCompany')
        else:
            messages.error(request, "Invalid form submission")
            return render(request, 'staffs/update_profile.html', context)

    context = {"form": form}
    return render(request, 'staffs/update_profile.html', context)


@login_required(login_url='company:staffLogin')
@user_passes_test(superuser_check, login_url="permission_error")
def employeeManagementPage(request):
    """
    employee management page, where employee basic information will get
    rendered in the page
    """
    query = request.GET.get('q')
    users = get_user_model().objects.filter(is_staff=True)
    if query is not None:
        lookup = Q(email__icontains=query) | Q(
            first_name__icontains=query) | Q(last_name__icontains=query)
        users = users.filter(lookup)

    context = {'employees': users}
    return render(request, 'employeeManagement/employeeManagement.html',
                  context)


@login_required(login_url='company:staffLogin')
@user_passes_test(superuser_check, login_url="permission_error")
def staffUpdatePage(request, pk):
    """
    while form showing the selected instance of the staff details
    and letting admin to edit and update the information. Also prevent
    accessing client here.
    """
    staff = get_user_model().objects.get(pk=pk)
    if staff.is_staff:
        form = CustomUserChangeForm(instance=staff)
        context = {'form': form, 'staff': staff}

        if request.method == 'POST':
            form = CustomUserChangeForm(request.POST or None, instance=staff)
            if form.is_valid():
                staff.email = form.cleaned_data['email']
                staff.username = form.cleaned_data['username']
                staff.first_name = form.cleaned_data['first_name']
                staff.last_name = form.cleaned_data['last_name']
                staff.gender = form.cleaned_data['gender']
                staff.contact_number = form.cleaned_data['contact_number']
                staff.contact_number_2 = form.cleaned_data['contact_number_2']
                staff.address = form.cleaned_data['address']
                staff.address_2 = form.cleaned_data['address_2']
                staff.city = form.cleaned_data['city']
                staff.province = form.cleaned_data['province']
                staff.country = form.cleaned_data['country']
                staff.is_client = False
                staff.is_staff = True
                staff.is_active = form.cleaned_data['is_active']
                staff.is_superuser = form.cleaned_data['is_superuser']
                staff.is_photographer = form.cleaned_data['is_photographer']
                staff.save()
                if staff.is_active:
                    messages.success(
                        request, f'Successfully updated records for {staff}')
                    return redirect('company:employeeManagement')
                else:
                    messages.success(request, f'Deactivated {staff}')
                    return redirect('company:employeeManagement')
            else:
                messages.error(request, 'Form is entered with invalid records')
                return render(request, 'employeeManagement/employee.html',
                              context)

        return render(request, 'employeeManagement/employee.html', context)
    else:
        username = staff.username
        messages.error(request, f'selected user {username} is not an employee')
        return render(request, '404.html')


@login_required(login_url='company:staffLogin')
@user_passes_test(superuser_check, login_url="permission_error")
def staffAddPage(request):
    """
    Adding new employee
    """
    context = {}
    form = AccountCreationForm(user_type='staff')
    if request.method == 'POST':
        form = AccountCreationForm(request.POST, user_type='staff')
        if form.is_valid():
            user = form.save()
            messages.success(request, f'Account was created for {user}')
            return redirect('company:employeeManagement')
        else:
            messages.error(request, 'Invalid form submission')

    context = {'form': form}
    return render(request, 'employeeManagement/employeeAdd.html', context)


@login_required(login_url='company:staffLogin')
@user_passes_test(superuser_check, login_url="permission_error")
def clientManagementPage(request):
    """
    client management page, where client basic information will get
    rendered in the page
    """
    query = request.GET.get('q')

tripod/company/templates/finance/invoice.html
{% extends 'admin_base.html' %}

{% block sidebar %}
{% include 'sidebars/company_sidebar.html' %}
{% endblock sidebar %}

{% block content %}

<div class="col">
  <div class="">
    <section class="jumbotron text-left">
      <h1 class="jumbotron-heading">Invoices</h1>
      <!-- <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p> -->
      <div class="d-flex justify-content-between align-items-center w-100">
        <form action={% url 'company:invoiceManagement'%} method='GET'>
          <input class="btn btn-outline-secondary" type="text" name="q" />
          <input class="btn btn-secondary my-2" type="submit" value="search"/>
        </form>
      </div>
    </section>
    <hr>

    <!-- <h6 class="text-muted">List of Employees</h6> -->
    <table class="table text-left align-middle">
      <thead class="thead-light">
        <tr>
          <th>Job</th>
          <th>Issue Date</th>
          <th>Net Price</th>
          <th>Paid amount</th>
          <th>To be Paid</th>
          <th>Last Paid Date</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for invoice in invoices %}
          <tr>
            {% if invoice.job %}
              <th>
                <a class="nav-link" href="{% url 'company:invoiceDetail' invoice.id %}">{{ invoice.job }}</a>
              </th>
            {% else %}
              <th>
                <a class="nav-link" href="{% url 'company:invoiceDetail' invoice.id %}">Invoice Job is deleted</a>
              </th>
            {% endif %}
            <th>{{ invoice.issue_date|date }}</th>
            <th>{{ invoice.total_price }}</th>
            <th>{{ invoice.paid }}</th>
            <th>{{ invoice.to_be_paid }}</th>
            <th>{{ invoice.last_paid_date|date }}</th>
            {% if invoice.job is None or invoice.job.id == '' %}
            <th>
              <a class="btn btn-outline-danger btn-sm" href="{% url 'company:invoiceDeletePage' invoice.id %}">Delete Invoice</a>
            </th>
            {% else %}
            <th><a class="nav-link" href="{% url 'job:jobPage' invoice.job.id %}">Go to Job</a></th>
            {% endif %}
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock content %}

tripod/company/templates/finance/invoiceDetail.html
{% extends 'admin_base_without_nav.html' %}

{% block sidebar %}
{% include 'sidebars/company_sidebar.html' %}
{% endblock sidebar %}

{% block content %}

<div class="col">
  <h5 class="display-5">Invoice
    <small class="text-muted">
      {% if invoice.job %}
        <a href="{% url 'job:jobPage' invoice.job.id %}">{{ invoice.job }}</a>
      {% else %}
        <p>Job is deleted</p>
      {% endif %}
    </small>
  </h5>
    <div class="row">
      <div class="col-sm-6">
        <p><strong>Invoice number: </strong>{{ invoice.get_issue_number }}</p>
        <p><strong>Invoice date: </strong>{{ invoice.issue_date }}</p>
      </div>
      <div class="col-sm-6">
        <p><strong>Due date: </strong>{{ invoice.full_pay_due_date }}</p>
      </div>
    <div>
    <div class="row">
      <div class="col-sm-6">
        <div class="card">
          <div class="card-body">
            <div class="row">
              <div class="col-sm-6">
                <p>Company</p>
              </div>
              <div class="col-sm-6">
                <p><strong>{{ company.name }}</strong></p>
              </div>
            </div>
            <hr>
            <h6>Contact Details</h6>
            <ul class="list-unstyled">
              <small>
              <li>{{ company.address1 | default:"-" }}, {{ company.address2 | default:"" }}</li>
              <li>{{ company.city | default:"-" }}</li>
              <li>{{ company.contact_number | default:"-"  }}</li>
              <li>{{ company.contact_email | default:"-"  }}</li>
              </small>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="card">
          <div class="card-body">
            <div class="row">
              <div class="col-sm-6">
                <p>Client</p>
              </div>
              <div class="col-sm-6">
                <p><strong>{{ invoice.job.primary_client.username }}</strong></p>
              </div>
            </div>
            <hr>
            <h6>Contact Details</h6>
            <ul class="list-unstyled">
              <small>
              <li>{{ invoice.job.primary_client.address  | default:"address1" }}, {{ cinvoice.job.primary_client.address2 | default:"" }}</li>
              <li>{{ invoice.job.primary_client.city | default:"city" }}</li>
              <li>{{ invoice.job.primary_client.contact_number | default:"contact number"  }}</li>
              <li>{{ invoice.job.primary_client.email | default:"contact email"  }}</li>
              </small>
            </ul>
          </div>
        </div>
      </div>
    </div>
  <br>

    <br>
    <br>
    <h5 class="display-6">Billing</h5>
    <hr>
    {% if invoice.job.package %}
      <h6>Select package : {{ invoice.job.package }}</h6>
      <table class="table table-stripped table-sm">
        <thead>
          <tr>
            <th>Item</th>
            <th>QTY</th>
            <th>Unit Price</th>
            <th>Sub Total</th>
          </tr>
        </thead>
        <tbody>
          {% for item in pkgLink %}
          <tr>
            <th>{{ item.product }}</th>
            <th>{{ item.units }}</th>
            <th>{{ item.product.unit_price }}</th>
            <th>{{ item.price }}</th>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
    <h6>Please select package</h6>
    {% endif %}
    <br>

    <div class="row">
      <div class="col-sm-6">
        <p><strong>Notes: </strong></p>
        <small>{{ invoice.notes | default:"" }}</small>
      </div>
      <div class="col-sm-6">
        <table class="table table-stripped table-sm">
          <thead>
            <tr>
              <th>Invoice Summary</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th>Subtotal</th>
              <th>{{ invoice.price }}</th>
            </tr>
            <tr>
              <th>Discount</th>
              <th>{{ invoice.discount }}</th>
            </tr>
            <tr>
              <th>Total</th>
              <th>{{ invoice.total_price }}</th>
            </tr>
          </tbody>
        </table>
        {% if invoice.job.get_job_completion_in_numbers < 3 or invoice.job.get_job_completion_in_numbers is None %}
          <a href="{% url 'job:jobUpdateInvoice' invoice.id %}" class="btn btn-primary">Update Invoice</a>
        {% else %}
          <a href="{% url 'job:jobUpdateInvoice' invoice.id %}" class=" disabled btn btn-primary">Invoice already sent</a>
        {% endif %}

      </div>
    <div>
    <br>
    <br>

    <h5 class="display-6">Payments</h5>
    <hr>
    <div class="row">
      <div class="col-sm-6">
        <p><strong>Paid: </strong>{{ invoice.paid }}</p>
        <p><strong>Last Paid Date: </strong>{{ invoice.last_paid_date | date }}</p>
      </div>
      <div class="col-sm-6">
        <p><strong>Remaining Payment: </strong>{{ invoice.to_be_paid }}</p>
      </div>
    <div>
    <br>
    <br>
    <h5>Payment History</h5>
    <table class="table table-stripped table-sm">
      <thead>
        <tr>
          <th>Paid Date</th>
          <th>Payment Method</th>
          <th>Payment</th>
        </tr>
      </thead>
      <tbody>
        {% for ph in invoice.paymenthistory_set.all %}
        <tr>
          <th>{{ ph.payment_date | date }}</th>
          <th>{{ ph.payment_method }}</th>
          <th>{{ ph.payment_amount }}</th>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% if invoice.job %}
      {% if not invoice.job.invoiced_client %}
        <a href="{% url 'job:addPayHistoryPage' invoice.job.id %}" class="btn btn-primary">Add paid record</a>
      {% else %}
        <a class="disabled btn btn-primary">Invoiced Client</a>
      {% endif %}
    {% else %}
    <p>Job is deleted</p>
    {% endif %}
</div>

{% endblock content %}